### ISSUE TITLE
pulp-run: Error while building component [/sys/board/chip/soc/cluster/l1_ico/interleaver]

### ISSUE THREAD

**Issue by bkr10** [pulp-platform/pulp-sdk#21] opened 2018-06-07 03:39 UTC
Hi,

I've successfully built pulp-sdk using the patch 79daee01e5fc21b6d833c68e866a148e98f11f90 (Fixed regressions). 

Steps followed to build pulp-sdk:
1) export PULP_RISCV_GCC_TOOLCHAIN=<path to the folder containing the bin folder of the toolchain>
2) source configs/pulp.sh

Now, I'm trying to launch the virtual platform, as below (by providing the correct paths where the files reside)
pulp-run --platform=vp --dir=work_dir --config-file=config.json

But the virtual platform build fails as below,

0: 0: [/sys/board/chip/soc/cluster/l1_ico/pe6_ico/py_comp] Building component
0: 0: [/sys/board/chip/soc/cluster/l1_ico/pe6_ico/py_comp] Building implementation
0: 0: [/sys/board/chip/soc/cluster/l1_ico/py_comp        ] New component (name: pe7_ico, class: interco/router)
0: 0: [/sys/board/chip/soc/cluster/l1_ico/pe7_ico/py_comp] Building component
0: 0: [/sys/board/chip/soc/cluster/l1_ico/pe7_ico/py_comp] Building implementation
0: 0: [/sys/board/chip/soc/cluster/l1_ico/py_comp        ] New component (name: interleaver, class: pulp/cluster/l1_interleaver)
0: 0: [/sys/board/chip/soc/cluster/l1_ico/interleaver/py_comp] Building component
0: 0: [/sys/board/chip/soc/cluster/l1_ico/interleaver/py_comp] Building implementation
**0: 0: [/sys/board/chip/soc/cluster/l1_ico/interleaver]
Caught error while building component (path: /sys/board/chip/soc/cluster/l1_ico/interleaver)**

I did a strace to get more info,
stat("PULP-2.0/pulp-sdk/pkg/sdk/dev/install/ws/python/debug/pulp/cluster/l1_interleaver_impl.so", {st_mode=S_IFREG|0755, st_size=388072, ...}) = 0
openat(AT_FDCWD, "PULP-2.0/pulp-sdk/pkg/sdk/dev/install/ws/python/debug/pulp/cluster/l1_interleaver_impl.so", O_RDONLY|O_CLOEXEC) = 3
fstat(3, {st_mode=S_IFREG|0755, st_size=388072, ...}) = 0
ioctl(3, TCGETS, 0x7ffccb19b900)        = -1 ENOTTY (Inappropriate ioctl for device)
lseek(3, 0, SEEK_CUR)                   = 0
openat(AT_FDCWD, "PULP-2.0/pulp-sdk/pkg/sdk/dev/install/ws/python/debug/pulp/cluster/l1_interleaver_impl.so", O_RDONLY|O_CLOEXEC) = 4
read(4, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0 \"\0\0\0\0\0\0"..., 832) = 832
fstat(4, {st_mode=S_IFREG|0755, st_size=388072, ...}) = 0
mmap(NULL, 2117888, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 4, 0) = 0x7f63e9c69000
mprotect(0x7f63e9c6d000, 2097152, PROT_NONE) = 0
mmap(0x7f63e9e6d000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 4, 0x4000) = 0x7f63e9e6d000
close(4)                                = 0
mprotect(0x7f63e9e6d000, 4096, PROT_READ) = 0
close(3)                                = 0
write(1, "0: 0: [\33[94m/sys/board/chip/soc/"..., 910: 0: [/sys/board/chip/soc/cluster/l1_ico/interleaver/py_comp] Building component
) = 91
write(1, "0: 0: [\33[94m/sys/board/chip/soc/"..., 960: 0: [/sys/board/chip/soc/cluster/l1_ico/interleaver/py_comp] Building implementation
) = 96
write(1, "0: 0: [\33[91m/sys/board/chip/soc/"..., 650: 0: [/sys/board/chip/soc/cluster/l1_ico/interleaver]
) = 65
write(1, "Caught error while building comp"..., 93Caught error while building component (path: /sys/board/chip/soc/cluster/l1_ico/interleaver)
) = 93
rt_sigaction(SIGINT, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7f63f067d890}, {sa_handler=0x7f63ec007c60, sa_mask=[INT], sa_flags=SA_RESTORER|SA_RESTART, sa_restorer=0x7f63ef6c4f20}, 8) = 0

Could you please let me know why is the error?
Please let me know if there are any steps I've missed out.

Also, its mentioned here https://github.com/pulp-platform/pulp-sdk#dependencies-setup, "RTL platforms should also be built separately", as part of dependency. Should I build the pulp-platform/pulp (8 core cluster) & setup 'VSIM_PATH' before building the virtual platform using pulp-run?

Thanks so much!

**Comment by haugoug** [comment] 2018-06-07 07:14
I can't reproduce this issue could you try again with the new version and let me know ?

**Comment by bkr10** [comment] 2018-06-08 04:19
I checked out the latest patch ecbb3eb49fc17e6b9523f9ce0423bb6bf3aafccc & the build succeeded.

But when I try to run the hello test program using virtual platform, it still fails as below. 
0: 0: [/sys/board/chip/soc/cluster/l1_ico/interleaver]
Caught error while building component (path: /sys/board/chip/soc/cluster/l1_ico/interleaver)

Steps followed:
1) source pkg/sdk/dev/sourceme.sh
2) Checked out pulp-rt-examples under pulp-sdk directory.
3) make clean all run

Ensured all the variables are set. When I echo $PULP_CURRENT_CONFIG, it is set as pulp@user_config_file=PULP/pulp-sdk/configs/json/pulp.json

Under pulp-rt-examples/hello, when I do make clean all run,
1) It produces test.o, tr_conf.o & rt_pad_conf.o in their respective directories.
2) Then when it tries to build the vp by invoking pulp-run it fails with the below error.

pulp-run --platform=vp --dir=hello/build/pulp --config-file=hello/build/pulp/config.json  prepare
pulp-run --platform=vp --dir=hello/build/pulp --config-file=hello/build/pulp/config.json
0: 0: [/sys/board/chip/soc/cluster/l1_ico/interleaver]
Caught error while building component (path: /sys/board/chip/soc/cluster/l1_ico/interleaver)
hello/build/pulp/__rules.mk:176: recipe for target 'run' failed

I tried to debug more on this error using strace and pdb & below are the things I found.

1) strace:
strace shows this.

stat("/PULP/pulp-sdk/pkg/sdk/dev/install/ws/bin/pulp/__init__.py", 0x7ffcfdfb3570) = -1 ENOENT (No such file or directory)
stat("PULP/pulp-sdk/pkg/sdk/dev/install/ws/bin/pulp/__init__.pyc", 0x7ffcfdfb3570) = -1 ENOENT (No such file or directory)
stat("PULP/pulp-sdk/pkg/sdk/dev/install/ws/bin/pulp.cpython-36m-x86_64-linux-gnu.so", 0x7ffcfdfb3570) = -1 ENOENT (No such file or directory)
stat("PULP/pulp-sdk/pkg/sdk/dev/install/ws/bin/pulp.abi3.so", 0x7ffcfdfb3570) = -1 ENOENT (No such file or directory)
stat("PULP/pulp-sdk/pkg/sdk/dev/install/ws/bin/pulp.so", 0x7ffcfdfb3570) = -1 ENOENT (No such file or directory)
stat("PULP/pulp-sdk/pkg/sdk/dev/install/ws/bin/pulp.py", 0x7ffcfdfb3570) = -1 ENOENT (No such file or directory)
stat("PULP/pulp-sdk/pkg/sdk/dev/install/ws/bin/pulp.pyc", 0x7ffcfdfb3570) = -1 ENOENT (No such file or directory)
stat("PULP/pulp-sdk/pkg/sdk/dev/install/ws/python/pulp/__init__.py", {st_mode=S_IFREG|0664, st_size=0, ...}) = 0
stat("PULP/pulp-sdk/pkg/sdk/dev/install/ws/python/pulp/cluster/__init__.py", {st_mode=S_IFREG|0664, st_size=0, ...}) = 0
stat("PULP/pulp-sdk/pkg/sdk/dev/install/ws/python/pulp/cluster/l1_interleaver_impl/__init__.py", 0x7ffcfdfb3570) = -1 ENOENT (No such file or directory)
stat("PULP/pulp-sdk/pkg/sdk/dev/install/ws/python/pulp/cluster/l1_interleaver_impl/__init__.pyc", 0x7ffcfdfb3570) = -1 ENOENT (No such file or directory)
stat("PULP/pulp-sdk/pkg/sdk/dev/install/ws/python/pulp/cluster/l1_interleaver_impl.cpython-36m-x86_64-linux-gnu.so", 0x7ffcfdfb3570) = -1 ENOENT (No such file or directory)
stat("PULP/pulp-sdk/pkg/sdk/dev/install/ws/python/pulp/cluster/l1_interleaver_impl.abi3.so", 0x7ffcfdfb3570) = -1 ENOENT (No such file or directory)
stat("PULP/pulp-sdk/pkg/sdk/dev/install/ws/python/pulp/cluster/l1_interleaver_impl.so", {st_mode=S_IFREG|0755, st_size=409184, ...}) = 0
openat(AT_FDCWD, "PULP/pulp-sdk/pkg/sdk/dev/install/ws/python/pulp/cluster/l1_interleaver_impl.so", O_RDONLY|O_CLOEXEC) = 3
fstat(3, {st_mode=S_IFREG|0755, st_size=409184, ...}) = 0
ioctl(3, TCGETS, 0x7ffcfdfb34a0)        = -1 ENOTTY (Inappropriate ioctl for device)
lseek(3, 0, SEEK_CUR)                   = 0
openat(AT_FDCWD, "PULP/pulp-sdk/pkg/sdk/dev/install/ws/python/pulp/cluster/l1_interleaver_impl.so", O_RDONLY|O_CLOEXEC) = 4
read(4, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0000\37\0\0\0\0\0\0"..., 832) = 832
fstat(4, {st_mode=S_IFREG|0755, st_size=409184, ...}) = 0
mmap(NULL, 2113736, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 4, 0) = 0x7fc0890c0000
mprotect(0x7fc0890c4000, 2093056, PROT_NONE) = 0
mmap(0x7fc0892c3000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 4, 0x3000) = 0x7fc0892c3000
close(4)                                = 0
mprotect(0x7fc0892c3000, 4096, PROT_READ) = 0
close(3)                                = 0
write(1, "0: 0: [\33[91m/sys/board/chip/soc/"..., 650: 0: [/sys/board/chip/soc/cluster/l1_ico/interleaver]
) = 65
write(1, "Caught error while building comp"..., 93Caught error while building component (path: /sys/board/chip/soc/cluster/l1_ico/interleaver)
) = 93

I checked the shared object l1_interleaver_impl.so as below. 
l1_interleaver_impl.so: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=0d4b3bacb7c58cb1eeb98bc19f2504dc22dbdc40, with debug_info, not stripped

2) pdb
I tried debugging the pulp-run using pdb. I invoked pulp-run directly by passing all the necessary parameters.

pdb pulp-run --platform=vp --dir=PULP/pulp-sdk/pulp-rt-examples/hello/build/pulp --config-file=PULP/pulp-sdk/pulp-rt-examples/hello/build/pulp/config.json

Below are the things I encountered. I'm not not too sure if this has something to do with the error, /sys/board/chip/soc/cluster/l1_ico/interleaver.

a)  Missing __init__.py under userconfig & padframe.
File "pkg/sdk/dev/install/ws/bin/pulp-run", line 33, in <module>
    from plp_runner import *
  File "PULP/pulp-sdk/pkg/sdk/dev/install/ws/python/plp_runner.py", line 29, in <module>
    import plptree
  File "pkg/sdk/dev/install/ws/bin/plptree.py", line 24, in <module>
    import userconfig.top
ImportError: No module named userconfig.top

I placed __init__.py in the userconfig directory. Then the below error occured,


File "pkg/sdk/dev/install/ws/bin/pulp-run", line 33, in <module>
    from plp_runner import *
  File "PULP/pulp-sdk/pkg/sdk/dev/install/ws/python/plp_runner.py", line 29, in <module>
    import plptree
  File "pkg/sdk/dev/install/ws/bin/plptree.py", line 27, in <module>
    import Regmap as regmap
  File "pkg/sdk/dev/install/ws/bin/Regmap.py", line 21, in <module>
    from prettytable import PrettyTable
ImportError: No module named prettytable

But I've prettytable package. When I do pip list, I can see prettytable in there.
prettytable             0.7.2

I'm not able to proceed further in debugging the pulp-run beyond this point.

Please let me know more on this issue.

**Comment by haugoug** [comment] 2018-06-08 07:55
Ok I found the issue, it is missing return. You can modify platform/vp/models/pulp/cluster/l1_interleaver_impl.cpp and add "return 0;" at line 121 and recompile the vp with this command: plpbuild --m vp build --stdout.
I've pushed the fix, I will integrate it soon in the master.
Thanks a lot for you detailed report.

**Comment by bkr10** [comment] 2018-06-11 05:44
Thanks so much! That resolved the issue & now I'm able to run the pulp-rt examples on vp. 

Also it would be great if you could let me know if there is any API reference for pulp programming. I couldn't find it in github or under the repo pulp-sdk/doc.

Thanks!

**Comment by haugoug** [comment] 2018-06-11 07:38
The documentation gets generated here: pkg/sdk/dev/doc/sdk/index.html
You can also directly open the runtime API documentation here: pkg/sdk/dev/doc/runtime/index.html
This documentation is mainly focusing on the fabric controller for managing IOs. Do you more need something on cluster side for parallel computation ?

**Comment by bkr10** [comment] 2018-06-11 07:43
Great! Thanks for that. Yes, I'm looking for parallel computation on cluster as well.

**Comment by haugoug** [comment] 2018-06-11 07:49
Ok the cluster part is not very well documented, I will improve that this week and let you know. Meanwhile you can have a look at this example: pulp-rt-examples/cluster/fork

**Comment by bkr10** [comment] 2018-06-11 07:55
Sure! That would be of great help! 
I ran the fork program & also had a look at the calls made. But thanks for pointing me that.

**Closed** 2021-02-03 20:56 UTC
